namespace: ${IMAGE_TAG}
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- ingress-frontend.yaml

images:
- name: amazonaws.com/ricochet
  newName: ${ECR_REPOSITORY}
  newTag: ${IMAGE_TAG}

